[package]
name = "rusty"
version = "0.1.0"
edition = "2021"

[lib]
name="rusty"
crate-type = ["cdylib"]


[dependencies.pyo3]
version = "*"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]